# -*- coding: utf-8 -*-
"""comparison graphs for classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YfhLPAIUt1VJdN1aKY-yvoCY96dqz5x
"""

import matplotlib.pyplot as plt
import numpy as np

"""#  **Graph 1: Scaling vs No Scaling (The Best Models)**

* Purpose: Show whether scaling helps (for each dataset).

# 1) Suicide Dataset
"""

# Labels for Suicide Dataset
labels_suicide = [
    "80-20 Scaled \n (Random Forest)",
    "80-20 Non-Scaled \n (Random Forest)",
    "70-30 Scaled \n (Random Forest)",
    "70-30 Non-Scaled \n (Random Forest)"
]

# Best F1 scores (Top model per setting)
f1_suicide = [
    0.699039,  # 80-20 Scaled (Random Forest)
    0.699039,  # 80-20 Non-Scaled (Random Forest)
    0.683624,  # 70-30 Scaled (Random Forest)
    0.695018   # 70-30 Non-Scaled (Random Forest)
]

plt.figure()
plt.bar(labels_suicide, f1_suicide)
plt.ylabel("F1 Score")
plt.title("Suicide Dataset: F1 Comparison (80-20 vs 70-30)")
plt.ylim(0.6, 0.72)
plt.show()

plt.show()

"""= This shows non-scaled results produce a higher F1 score compared to scaled dataset

# 2) Fused Dataset
"""

# Labels for Fused Dataset
labels_fused = [
    "80-20 Scaled \n (SVM)",
    "80-20 Non-Scaled\n (SVM)",
    "70-30 Scaled \n(ANN)",
    "70-30 Non-Scaled\n (Naive Bayes)"
]

# Best F1 scores (Top model per setting)
f1_fused = [
    0.658262,  # 80-20 Scaled (SVM)
    0.642985,  # 80-20 Non-Scaled (SVM)
    0.658356,  # 70-30 Scaled (ANN)
    0.643151   # 70-30 Non-Scaled (Naive Bayes)
]

plt.figure()
plt.bar(labels_fused, f1_fused)
plt.ylabel("F1 Score")
plt.title("Fused Dataset: F1 Comparison (80-20 vs 70-30)")
plt.ylim(0.6, 0.7)
plt.show()

"""= This shows scaled results produce a higher F1 score compared to non-scaled dataset

# **Graph 2 :Comparison between GridSearch And RandomSearch**

* Purpose:

  Show which model performed best for:

1) Suicide dataset

2) Fused dataset#

# 1) Non-scaled Suicide Dataset (it has higher F1 score)
"""

models_suicide = ["Random Forest", "Decision Tree", "KNN"]

grid_f1_suicide = [
    0.6977,  # Random Forest
    0.6933,  # Decision Tree
    0.6986   # KNN
]

random_f1_suicide = [
    0.6985,  # Random Forest
    0.6890,  # Decision Tree
    0.6884   # KNN
]

x = range(len(models_suicide))

plt.figure()
plt.bar(x, grid_f1_suicide, width=0.4, label="Grid Search")
plt.bar([i + 0.4 for i in x], random_f1_suicide, width=0.4, label="Random Search")

plt.xticks([i + 0.2 for i in x], models_suicide)
plt.ylabel("F1 Score")
plt.title("Non-scaled Suicide Dataset\nGrid Search vs Random Search")
plt.legend()
plt.ylim(0.68, 0.71)
plt.show()

"""= This shows KNN provide the highest F1 score after using GridSearch tuning

# 2) Scaled Fused Dataset (Has higher F1 score)
"""

models_fused = ["SVM", "ANN", "XGBoost"]

grid_f1_fused = [
    0.6723,  # SVM
    0.6722,  # ANN
    0.6815   # XGBoost
]

random_f1_fused = [
    0.6723,  # SVM
    0.6531,  # ANN
    0.6737   # XGBoost
]

x = range(len(models_fused))

plt.figure()
plt.bar(x, grid_f1_fused, width=0.4, label="Grid Search")
plt.bar([i + 0.4 for i in x], random_f1_fused, width=0.4, label="Random Search")

plt.xticks([i + 0.2 for i in x], models_fused)
plt.ylabel("F1 Score")
plt.title("Scaled Fused Dataset\nGrid Search vs Random Search")
plt.legend()
plt.ylim(0.64, 0.70)
plt.show()

"""= This shows XGBoost provide the highest F1 score after using GridSearch

# **Graph 3: Comparison Between Manual Modeling And AutoML**

# 1) Suicide Dataset
"""

labels_suicide = [
    "Grid Search (KNN)",
    "AutoML (WeightedEnsemble L2)"
]

f1_suicide = [
    0.6986,    # Tuned KNN (Grid Search)
    0.716356  # AutoML - WeightedEnsemble L2
]

plt.figure()
plt.bar(labels_suicide, f1_suicide)
plt.ylabel("F1 Score")
plt.title("Non-scaled Suicide Dataset\nTuned Model vs AutoML")
plt.ylim(0.68, 0.73)
plt.show()

"""# 2) Fused Dataset"""

labels_fused = [
    "Grid Search (XGBoost)",
    "AutoML (LightGBM)"
]

f1_fused = [
    0.6815,    # Tuned XGBoost (Grid Search)
    0.679750  # AutoML - LightGBM
]

plt.figure()
plt.bar(labels_fused, f1_fused)
plt.ylabel("F1 Score")
plt.title("Scaled Fused Dataset\nTuned Model vs AutoML")
plt.ylim(0.50, 0.90)
plt.show()